// <auto-generated />
using System;
using Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20220914110455_CashBack_Routes")]
    partial class CashBack_Routes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.P2P.MainData.CashBack", b =>
                {
                    b.Property<int>("CashBackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CashBack_ca")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CashBack_terms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Exclusive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCampaign")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Valid_Until")
                        .HasColumnType("datetime2");

                    b.HasKey("CashBackId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CashBacks", "P2P");
                });

            modelBuilder.Entity("Entities.P2P.MainData.DataType", b =>
                {
                    b.Property<int>("DataTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DataTypeId");

                    b.ToTable("DataTypes", "P2P");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("LanguageId");

                    b.HasIndex("LanguageName");

                    b.ToTable("Languages", "P2P");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Links", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("UrlTableId")
                        .HasColumnType("int");

                    b.HasKey("LinkId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UrlTableId");

                    b.ToTable("Links", "P2P");
                });

            modelBuilder.Entity("Entities.P2P.MainData.ReviewAttribute", b =>
                {
                    b.Property<int>("ReviewAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DataTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReviewAttributeId");

                    b.HasIndex("DataTypeId");

                    b.ToTable("ReviewAttributes", "P2P");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Routes", b =>
                {
                    b.Property<int>("RoutesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DataTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("UrlTableId")
                        .HasColumnType("int");

                    b.HasKey("RoutesId");

                    b.HasIndex("DataTypeId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UrlTableId");

                    b.ToTable("Routes", "P2P");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Settings.FooterSettings", b =>
                {
                    b.Property<int>("FooterSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CopyrightNotice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacebookLink")
                        .HasColumnType("int");

                    b.Property<string>("FooterNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("LinkedInLink")
                        .HasColumnType("int");

                    b.Property<int>("PodcastLink")
                        .HasColumnType("int");

                    b.Property<int>("TwitterLink")
                        .HasColumnType("int");

                    b.Property<int>("YoutubeLink")
                        .HasColumnType("int");

                    b.HasKey("FooterSettingsId");

                    b.HasIndex("FacebookLink");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LinkedInLink");

                    b.HasIndex("PodcastLink");

                    b.HasIndex("TwitterLink");

                    b.HasIndex("YoutubeLink");

                    b.ToTable("FooterSettings", "Settings");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Settings.NavigationSettings", b =>
                {
                    b.Property<int>("NavigationSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Academy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AcademyRoute")
                        .HasColumnType("int");

                    b.Property<string>("Bonus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BonusRoute")
                        .HasColumnType("int");

                    b.Property<string>("Home")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HomeRoute")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("News")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NewsRoute")
                        .HasColumnType("int");

                    b.Property<string>("Reviews")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReviewsRoute")
                        .HasColumnType("int");

                    b.HasKey("NavigationSettingsId");

                    b.HasIndex("LanguageId");

                    b.ToTable("NavigationSettings", "Settings");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Testimonial", b =>
                {
                    b.Property<int>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("TagLine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestimonialText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TestimonialId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Testimonials", "P2P");
                });

            modelBuilder.Entity("Entities.P2P.MainData.UrlTable", b =>
                {
                    b.Property<int>("UrlTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DataTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UrlTableId");

                    b.HasIndex("DataTypeId");

                    b.ToTable("UrlTables", "P2P");
                });

            modelBuilder.Entity("Entities.P2P.MainData.CashBack", b =>
                {
                    b.HasOne("Entities.P2P.MainData.Language", "Language")
                        .WithMany("CashBacks")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Links", b =>
                {
                    b.HasOne("Entities.P2P.MainData.Language", "Language")
                        .WithMany("Links")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.P2P.MainData.UrlTable", "UrlTable")
                        .WithMany("Links")
                        .HasForeignKey("UrlTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("UrlTable");
                });

            modelBuilder.Entity("Entities.P2P.MainData.ReviewAttribute", b =>
                {
                    b.HasOne("Entities.P2P.MainData.DataType", "DataType")
                        .WithMany("ReviewAttributes")
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataType");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Routes", b =>
                {
                    b.HasOne("Entities.P2P.MainData.DataType", "DataType")
                        .WithMany("Routes")
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.P2P.MainData.Language", "Language")
                        .WithMany("Routes")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.P2P.MainData.UrlTable", "UrlTable")
                        .WithMany("Routes")
                        .HasForeignKey("UrlTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataType");

                    b.Navigation("Language");

                    b.Navigation("UrlTable");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Settings.FooterSettings", b =>
                {
                    b.HasOne("Entities.P2P.MainData.UrlTable", "FS_FacebookUrl")
                        .WithMany("FacebookUrls")
                        .HasForeignKey("FacebookLink")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.P2P.MainData.Language", "Language")
                        .WithMany("FooterSettings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.P2P.MainData.UrlTable", "FS_LinkedInUrl")
                        .WithMany("LinkedInUrls")
                        .HasForeignKey("LinkedInLink")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.P2P.MainData.UrlTable", "FS_PodcastUrl")
                        .WithMany("PodcastUrls")
                        .HasForeignKey("PodcastLink")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.P2P.MainData.UrlTable", "FS_TwitterUrl")
                        .WithMany("TwitterUrls")
                        .HasForeignKey("TwitterLink")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.P2P.MainData.UrlTable", "FS_YoutubeUrl")
                        .WithMany("YoutubeUrls")
                        .HasForeignKey("YoutubeLink")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FS_FacebookUrl");

                    b.Navigation("FS_LinkedInUrl");

                    b.Navigation("FS_PodcastUrl");

                    b.Navigation("FS_TwitterUrl");

                    b.Navigation("FS_YoutubeUrl");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Settings.NavigationSettings", b =>
                {
                    b.HasOne("Entities.P2P.MainData.Language", "Language")
                        .WithMany("NavigationSettings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Testimonial", b =>
                {
                    b.HasOne("Entities.P2P.MainData.Language", "Language")
                        .WithMany("Testimonials")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Entities.P2P.MainData.UrlTable", b =>
                {
                    b.HasOne("Entities.P2P.MainData.DataType", "DataType")
                        .WithMany("UrlTables")
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataType");
                });

            modelBuilder.Entity("Entities.P2P.MainData.DataType", b =>
                {
                    b.Navigation("ReviewAttributes");

                    b.Navigation("Routes");

                    b.Navigation("UrlTables");
                });

            modelBuilder.Entity("Entities.P2P.MainData.Language", b =>
                {
                    b.Navigation("CashBacks");

                    b.Navigation("FooterSettings");

                    b.Navigation("Links");

                    b.Navigation("NavigationSettings");

                    b.Navigation("Routes");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("Entities.P2P.MainData.UrlTable", b =>
                {
                    b.Navigation("FacebookUrls");

                    b.Navigation("LinkedInUrls");

                    b.Navigation("Links");

                    b.Navigation("PodcastUrls");

                    b.Navigation("Routes");

                    b.Navigation("TwitterUrls");

                    b.Navigation("YoutubeUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
